version: '3.8'

services:
  ticket_register:
    container_name: ticket-management-api
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: ticket_register
      MYSQL_PASSWORD: ticket_register_password
      MYSQL_HOST: ticket-register-db
      MYSQL_DATABASE: ticket_register
      MYSQL_CHARSET: utf8mb4
    ports:
      - "8080:8080"
    depends_on:
      - ticket_register_db

  ticket_register_db:
    image: mysql:8.0
    container_name: ticket-management-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: ticket_management
      MYSQL_PASSWORD: ticket_management_password
      MYSQL_DATABASE: ticket_management
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/delete_expire_ticket.sql:/docker-entrypoint-initdb.d/delete_expire_ticket.sql
